name: 'cmake-install'
description: 'cmake installation in linux based workflows'

inputs:
  os:
    description: 'operating system to run template on: linux/windows/ios'
    required: true
    default: 'linux'

env:
  version: 'cmake-4.1.0-rc3'

runs:
  using: "composite"
  steps:
    - name: linux-download-and-install-cmake
      if: contains(inputs.os, 'linux')
      run: |
        wget https://github.com/Kitware/CMake/releases/download/"{{ env.version }}"/"{{ env.version }}"-linux-x86_64.sh
        chmod +x "{{ env.version }}"-linux-x86_64.sh
        ./"{{ env.version }}"-linux-x86_64.sh --prefix=/opt/cmake --skip-license
        export PATH=/opt/cmake/bin:$PATH
        cmake --version
      shell: bash
    - name: windows-download-and-install-cmake
      if: contains(inputs.os, 'windows')
      run: |
        choco install cmake --version=${{ env.version }}
      shell: bash
    - name: ios-download-and-install-cmake
      if: contains(inputs.os, 'ios')
      run: |
        brew install cmake
      shell: bash
