name: 'cmake-install'
description: 'cmake installation in linux based workflows'

runs:
  using: "composite"
  steps:
    - name: download-and-install-cmake
      run: |
        sudo snap install cmake --channel=3.31 --classic
      shell: bash
