name: 'cmake-install'
description: 'cmake installation in linux based workflows'

inputs:
  os:
    description: 'operating system to run template on: linux/windows/ios'
    required: true
    default: 'linux'

env:
  version: '4.1.0-rc3'

runs:
  using: "composite"
  steps:
    - name: linux-download-and-install-cmake
      if: contains(inputs.os, 'linux')
      run: |
        wget https://github.com/Kitware/CMake/releases/download/cmake-"{{ env.version }}"/cmake-"{{ env.version }}"-linux-x86_64.sh
        chmod +x "cmake-{{ env.version }}"-linux-x86_64.sh
        ./cmake-"{{ env.version }}"-linux-x86_64.sh --prefix=/opt/cmake --skip-license
        export PATH=/opt/cmake/bin:$PATH
        cmake --version
      shell: bash
    - name: windows-download-and-install-cmake
      if: contains(inputs.os, 'windows')
      run: |
        choco install cmake --version=${{ env.version }}
      shell: bash
    - name: ios-download-and-install-cmake
      if: contains(inputs.os, 'ios')
      run: |
        version=${{ env.version }}
        curl -LO https://github.com/Kitware/CMake/releases/download/v${version}/cmake-${version}-macos-universal.tar.gz
        tar -xzf cmake-${version}-macos-universal.tar.gz
        sudo mv cmake-${version}-rc3-macos-universal /opt/cmake-${version}
        export PATH="/opt/cmake-${version}/CMake.app/Contents/bin:$PATH"
        source ~/.zshrc
      shell: bash
