name: 'python3 install'
description: 'python3 installation in linux based workflows'

runs:
  using: "composite"
  steps:
    - name: download-and-install-python3
      run: |
        sudo apt update && \
        sudo apt install build-essential software-properties-common -y && sudo add-apt-repository ppa:deadsnakes/ppa && \
        sudo apt update && \
        sudo apt install python3.13 python3.13-venv -y
      shell: bash
