name: 'python3 install'
description: 'python3 installation in linux based workflows'

inputs:
  os:
    description: 'operating system to run template on: linux/windows/ios'
    required: true
    default: 'linux'

runs:
  using: "composite"
  steps:
    - name: linux-download-and-install-python3
      if: contains(inputs.os, 'linux')
      run: |
        sudo apt update && \
        sudo apt install build-essential software-properties-common -y && sudo add-apt-repository ppa:deadsnakes/ppa && \
        sudo apt update && \
        sudo apt install python3.13 python3.13-venv -y
      shell: bash
    - name: windows-download-and-install-python3
      if: contains(inputs.os, 'windows')
      run: |
        choco install --force python3 --pre
      shell: bash
    - name: ios-download-and-install-python3
      if: contains(inputs.os, 'ios')
      run: |
        brew install python@3.13
      shell: bash
