name: linux-build-and-validation

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  BUILD_DIR: ${{ github.workspace }}/build
  TEST_DIR: ${{ github.workspace }}/build/tests

jobs:
  python-venv-setup:
    runs-on: [ 'ubuntu-22.04' ]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: python3-setting-up
      run: |
        sudo apt update && \
        sudo apt install build-essential software-properties-common -y && \
        sudo add-apt-repository ppa:deadsnakes/ppa && \
        sudo apt update && \
        sudo apt install python3.11 python3.11-venv -y

    - name: python3-venv
      run: |
        python3.11 -m venv venv && \
        source venv/bin/activate

  build-repository:
    needs: [ 'python-venv-setup' ]
    runs-on: [ 'ubuntu-22.04' ]

    steps:

    - name: look inside
      run: ls && python3 --version
