name: clang-format

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
   code-format:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Configure git
      run: git config --global user.email "${{ secrets.EMAIL }}" && git config --global user.name "${{ secrets.AGENT_NAME }}"

    - name: Code formatting
      run: ./scripts/run_clang_format.sh

    - name: Commit changes
      run: ./.github/workflows/scripts/commit_changes.sh
