name: clang-format

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
   code-format:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: de-vri-es/setup-git-credentials@v2.0.10
      with:
        credentials: ${{ secrets.GITHUB_TOKEN }}

    - name: setting-up-git
      run: git config --global user.name "${{ secrets.AGENT_NAME }}" && git config --global user.email "${{ secrets.EMAIL }}"

    - name: formatting code
      run: ./scripts/run_clang_format.sh

    - name: commiting changes
      run: ./.github/workflows/scripts/commit_changes.sh
