name: clang-format

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
   code-format:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: de-vri-es/setup-git-credentials@v2.1.2
      with:
        credentials: ${{ secrets.GITHUB_TOKEN }}

    - name: setting-up-git
      run: git config --global user.name "${{ secrets.AGENT_NAME }}" && git config --global user.email "${{ secrets.EMAIL }}"

    - name: formatting code
      run: ./scripts/run_clang_format.sh

    - name: setting up python3
      run: |
        sudo apt update &&\
        sudo apt install build-essential software-properties-common -y &&\
        sudo add-apt-repository ppa:deadsnakes/ppa &&\
        sudo apt update &&\
        sudo apt install python3.11 -y &&\
        python3 --version

    - name: python venv setting up
      run: |
        python3 -m venv venv &&\
        source venv/bin/activate

    - name: commiting changes
      run: python .github/workflows/scripts/commit_changes.py
