name: code-coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
        build-type:
          description: 'build type'
          required: true
          default: Debug
          type: choice
          options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

env:
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: configuring CMake
      run: cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=${{ inputs.build-type }}

    - name: building
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: generating code-coverage
      working-directory: ${{ env.BUILD_DIR }}
      run: ./generate_code_coverage_raport.sh
