name: code-coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DCOVERAGE=ON

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

    - name: Code coverage generation
      working-directory: ${{ github.workspace }}/build
      run: ./generate_code_coverage_raport.sh
