name: create-release

on:
  workflow_dispatch:
    inputs:
      release-number:
        description: 'Release number'
        required: true
      release-title:
        description: 'Release title'
        required: false

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: [ 'ubuntu-24.04' ]

    steps:
      - uses: actions/checkout@v5.0.0

      - name: setting-up-git
        uses: de-vri-es/setup-git-credentials@v2.1.2
        with:
          credentials: ${{ secrets.GITHUB_TOKEN }}

      - uses: milosz-barylowicz/cpp-projects-github-actions/python3-upgrade@main
        with:
            python3-version: '13'
            operating-system: 'ubuntu-24.04'

      - name: python-venv-setting-up
        run: |
          python3.13 -m venv venv && \
          source venv/bin/activate

      - name: creating-release
        if: inputs.release-title == ''
        run: |
          python ./.github/workflows/scripts/create_release.py --release_version ${{ inputs.release-number }}

      - name: creating-release-with-title
        if: inputs.release-title != ''
        run: |
          python ./.github/workflows/scripts/create_release.py --release_version ${{ inputs.release-number }} --release_title ${{ inputs.release-title }}
