name: delete-all-github-workflows-runs

on:
  schedule:
  - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  remove-all-runs:
    runs-on: [ 'ubuntu-22.04' ]
    permissions:
        actions: write
    steps:
      - name: workflows-runs-removing
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 30
            keep_minimum_runs: 0
