name: docker-build

on:
  pull_request:
    branches: [ 'main' ]

  schedule:
    - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ 'ubuntu-22.04' ]

    steps:
    - uses: actions/checkout@v4.1.4

    - name: python3-setting-up
      run: |
        sudo apt update && \
        sudo apt install build-essential software-properties-common -y && \
        sudo add-apt-repository ppa:deadsnakes/ppa && \
        sudo apt update && \
        sudo apt install python3.13 python3.13-venv -y

    - name: python-venv-setting-up
      run: |
        python3.13 -m venv venv && \
        source venv/bin/activate && \
        newgrp docker

    - name: docker-container-configuration-and-execution
      working-directory: ${{ github.workspace }}
      run: |
        python scripts/docker/build_and_run.py --user $(id -u) --group $(id -g)
