name: docker-build

on:
  pull_request:
    branches: [ 'main' ]

  schedule:
    - cron:  '0 3 * * SUN'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ 'ubuntu-24.04' ]

    steps:
    - uses: actions/checkout@v4.2.2

    - name: python3-install
      uses: ./.github/workflows/templates/python3-installation
      with:
        os: 'linux'

    - name: python-venv-setting-up
      run: |
        python3.13 -m venv venv && \
        source venv/bin/activate && \
        newgrp docker

    - name: docker-container-configuration-and-execution
      working-directory: ${{ github.workspace }}
      run: |
        python scripts/docker/build_and_run.py --user $(id -u) --group $(id -g)
