name: sanitizers

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/build
  TEST_DIR: ${{ github.workspace }}/build/tests

jobs:
  asan:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: configuring CMake
      run: cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} -DASan=ON

    - name: building
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: setting up python3
      run: |
        sudo apt update &&\
        sudo apt install build-essential software-properties-common -y &&\
        sudo add-apt-repository ppa:deadsnakes/ppa &&\
        sudo apt update &&\
        sudo apt install python3.11 -y &&\
        python3 --version

    - name: python venv setting up
      run: |
        python3 -m venv venv &&\
        source venv/bin/activate

    - name: running ASan
      working-directory: ${{ env.TEST_DIR }}
      run: python run_unit_tests.py

  ubsan:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: configuring CMake
      run: cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} -DUBSan=ON

    - name: building
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: setting up python3
      run: |
        sudo apt update &&\
        sudo apt install build-essential software-properties-common -y &&\
        sudo add-apt-repository ppa:deadsnakes/ppa &&\
        sudo apt update &&\
        sudo apt install python3.11 -y &&\
        python3 --version

    - name: python venv setting up
      run: |
        python3 -m venv venv &&\
        source venv/bin/activate

    - name: running USan
      working-directory: ${{ env.TEST_DIR }}
      run: python run_unit_tests.py

  lsan:
    runs-on: [ ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: configuring CMake
        run: cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} -DLSan=ON

      - name: building
        run: cmake --build ${{ env.BUILD_DIR }}

      - name: setting up python3
        run: |
          sudo apt update &&\
          sudo apt install build-essential software-properties-common -y &&\
          sudo add-apt-repository ppa:deadsnakes/ppa &&\
          sudo apt update &&\
          sudo apt install python3.11 -y &&\
          python3 --version

      - name: python venv setting up
        run: |
          python3 -m venv venv &&\
          source venv/bin/activate

      - name: running LSan
        working-directory: ${{ env.TEST_DIR }}
        run: python run_unit_tests.py
