name: sanitizers

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  asan:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DASan=ON

    - name: Build repository
      run: cmake --build ${{ github.workspace }}/build

    - name: Running ASan
      working-directory: ${{ github.workspace }}/build/tests
      run: ./run_all_unit_tests.sh

  ubsan:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DUBSan=ON

    - name: Build repository
      run: cmake --build ${{ github.workspace }}/build

    - name: Running USan
      working-directory: ${{ github.workspace }}/build/tests
      run: ./run_all_unit_tests.sh

  lsan:
    runs-on: [ ubuntu-22.04 ]

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }} -DLSan=ON

      - name: Build
        run: cmake --build ${{ github.workspace }}/build

      - name: Running LSan
        working-directory: ${{ github.workspace }}/build/tests
        run: ./run_all_unit_tests.sh
