name: unit-tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
    windows-based-unit-tests:
      strategy:
        matrix:
          os: [ windows-2022 ]
      env:
        BUILD_DIR: ${{ github.workspace }}\build
        TEST_DIR: ${{ github.workspace }}\build\tests

      runs-on: ${{ matrix.os }}

      steps:
      - uses: actions/checkout@v4.1.4

      - name: CMake-package-update
        run: |
          choco install cmake

      - name: project-building
        run: |
          cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} &&
          cmake --build ${{ env.BUILD_DIR }}

      - name: unit-tests-executing
        working-directory: ${{ env.TEST_DIR }}
        run: python3 run_unit_tests.py

    macos-based-unit-tests:
      strategy:
        matrix:
          os: [ 'macos-14' ]

      env:
        BUILD_DIR: ${{ github.workspace }}/build
        TEST_DIR: ${{ github.workspace }}/build/tests

      runs-on: ${{ matrix.os }}

      steps:
      - uses: actions/checkout@v4.1.4

      - name: CMake-package-update
        run: |
          brew upgrade cmake

      - name: building
        run: |
          cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} && \
          cmake --build ${{ env.BUILD_DIR }}

      - name: unit-tests-executing
        working-directory: ${{ env.TEST_DIR }}
        run: python run_unit_tests.py
