name: unit-tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
    windows-based-unit-tests:
      env:
        BUILD_DIR: ${{ github.workspace }}\build
        TEST_DIR: ${{ github.workspace }}\build\tests

      runs-on: [ 'windows-2022' ]

      steps:
      - uses: actions/checkout@v5.0.0
      - uses: milosz-barylowicz/cpp-projects-github-actions/cmake-upgrade@v1.0.0
        with:
          cmake-version: '3.30.3'
          target-os: 'windows-2022'
      - uses: milosz-barylowicz/cpp-projects-github-actions/python3-upgrade@v1.0.0
        with:
            python3-version: '13'
            operating-system: 'windows-2022'

      - name: project-building
        run: |
          cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} &&
          cmake --build ${{ env.BUILD_DIR }}

      - name: unit-tests-executing
        working-directory: ${{ env.TEST_DIR }}
        run: |
          python3 run_unit_tests.py

    macos-based-unit-tests:
      env:
        BUILD_DIR: ${{ github.workspace }}/build
        TEST_DIR: ${{ github.workspace }}/build/tests

      runs-on: [ 'macos-14' ]

      steps:
      - uses: actions/checkout@v4.2.2
      - uses: milosz-barylowicz/cpp-projects-github-actions/cmake-upgrade@v1.0.0
        with:
          cmake-version: '3.30.3'
          target-os: 'macos-14'
      - uses: milosz-barylowicz/cpp-projects-github-actions/python3-upgrade@v1.0.0
        with:
            python3-version: '13'
            operating-system: 'macos-14'

      - name: building
        run: |
          cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} && \
          cmake --build ${{ env.BUILD_DIR }}

      - name: unit-tests-executing
        working-directory: ${{ env.TEST_DIR }}
        run: python run_unit_tests.py
