name: unit-tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
    windows-based-unit-tests:
      env:
        BUILD_DIR: ${{ github.workspace }}\build
        TEST_DIR: ${{ github.workspace }}\build\tests

      runs-on: [ 'windows-2022' ]

      steps:
      - uses: actions/checkout@v4.2.2

      - name: CMake-package-update
        uses: ./.github/workflows/templates/cmake-installation
        with:
          os: 'windows'

      - name: python3-install
        uses: ./.github/workflows/templates/python3-installation
        with:
          os: 'windows'

      - name: project-building
        run: |
          cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} &&
          cmake --build ${{ env.BUILD_DIR }}

      - name: unit-tests-executing
        working-directory: ${{ env.TEST_DIR }}
        run: python3 run_unit_tests.py

    macos-based-unit-tests:
      env:
        BUILD_DIR: ${{ github.workspace }}/build
        TEST_DIR: ${{ github.workspace }}/build/tests

      runs-on: [ 'macos-14' ]

      steps:
      - uses: actions/checkout@v4.2.2

      - name: CMake-package-update
        uses: ./.github/workflows/templates/cmake-installation
        with:
          os: 'ios'

      - name: python3-install
        uses: ./.github/workflows/templates/python3-installation
        with:
          os: 'ios'

      - name: building
        run: |
          cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }} && \
          cmake --build ${{ env.BUILD_DIR }}

      - name: unit-tests-executing
        working-directory: ${{ env.TEST_DIR }}
        run: python run_unit_tests.py
