name: valgrind

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build

    - name: Installing valgrind
      run: sudo apt update --fix-missing && sudo apt install valgrind

    - name: Running valgrind
      working-directory: ${{ github.workspace }}/build/tests
      run: ./run_valgrind.sh
