name: valgrind

on:
  push:
    branches: [ '**' ] # '**' it used to match all existing branches
  pull_request:
    branches: [ '**' ] # '**' it used to match all existing branches
  workflow_dispatch:   # workflow dispatch is enabling 'Re-run all jobs' button in github UI
 
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Installing valgrind
      run: sudo apt install valgrind

    - name: Running valgrind
      working-directory: ${{github.workspace}}/build/tests
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: 
        cd ${{github.workspace}}/build/tests/array_test_suite && valgrind -s -v --error-exitcode=1 --leak-check=full ./array_test_suite &&
        cd ${{github.workspace}}/build/tests/stack_test_suite && valgrind -s -v --error-exitcode=1 --leak-check=full ./stack_test_suite &&
        cd ${{github.workspace}}/build/tests/vector_test_suite && valgrind -s -v --error-exitcode=1 --leak-check=full ./vector_test_suite &&
        cd ${{github.workspace}}/build/tests/list_test_suite && valgrind -s -v --error-exitcode=1 --leak-check=full ./list_test_suite
