name: valgrind

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/build
  TEST_DIR: ${{ github.workspace }}/build/tests

jobs:
  build:
    runs-on: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v4.1.1

    - name: configuring CMake
      run: cmake -B ${{ env.BUILD_DIR }} -S ${{ github.workspace }}

    - name: building
      run: cmake --build ${{ env.BUILD_DIR }}

    - name: Installing valgrind
      run: sudo apt update --fix-missing && sudo apt install valgrind

    - name: running valgrind
      working-directory: ${{ env.TEST_DIR }}
      run: ./run_valgrind.sh
